// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using ProjectManagementAPI.Infrastructure.Data;

#nullable disable

namespace ProjectManagementAPI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectManagementAPI.Core.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasDefaultValue("User").HasColumnType("nvarchar(50)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("ProjectManagementAPI.Core.Domain.Entities.Project", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Projects");
            });

            modelBuilder.Entity("ProjectManagementAPI.Core.Domain.Entities.ProjectTask", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<DateTime?>("DueDate").HasColumnType("datetime2");
                b.Property<string>("Priority").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("ProjectId");
                b.ToTable("Tasks");
            });

            modelBuilder.Entity("ProjectManagementAPI.Core.Domain.Entities.Project", b =>
            {
                b.HasOne("ProjectManagementAPI.Core.Domain.Entities.User", "User")
                    .WithMany("Projects")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("ProjectManagementAPI.Core.Domain.Entities.ProjectTask", b =>
            {
                b.HasOne("ProjectManagementAPI.Core.Domain.Entities.Project", "Project")
                    .WithMany("Tasks")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Project");
            });

            modelBuilder.Entity("ProjectManagementAPI.Core.Domain.Entities.User", b =>
            {
                b.Navigation("Projects");
            });

            modelBuilder.Entity("ProjectManagementAPI.Core.Domain.Entities.Project", b =>
            {
                b.Navigation("Tasks");
            });
#pragma warning restore 612, 618
        }
    }
}
